# Site settings
title: How to Meet WCAG 2.0
email: ee@w3.org
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
status: draft

techniqueurl: http://www.w3.org/TR/WCAG20-TECHS/

port: 4099

safe: true
lsi: false

# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false

collections:
  filters:
    output: false
  help:
    output: false

exclude:
  - node_modules
  - .sass-cache
  - Gemfile.lock
  - Gemfile
  - gulpfile.js
  - npm-debug.log
  - package.json
  - questions.md