# Site settings
title: "How to Meet WCAG 2 (Quickref Reference)"
email: ee@w3.org
description: ""
#baseurl: "/wai-wcag-quickref/" # the subpath of your site, e.g. /blog/
#baseurl: "/WAI/WCAG20/quickref/" # For publication
#baseurl: /
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
status: draft
version: "2.5"

techniqueurl: https://www.w3.org/TR/WCAG21-TECHS/
understandingurl: https://www.w3.org/WAI/WCAG21/Understanding/

port: 4099

safe: true
lsi: false

# Build settings
markdown: kramdown

repository: 'w3c/wai-wcag-quickref'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false

collections:
  filters:
    output: false
  help:
    output: false


plugins:
  - jekyll-github-metadata

exclude:
  - node_modules
  - .sass-cache
  - Gemfile.lock
  - Gemfile
  - gulpfile.js
  - npm-debug.log
  - package.json
  - questions.md
